---
version: "2.1"
services:
  tachidesk-docker:
    image: docker.io/arbuild/tachidesk-docker
    container_name: tachidesk-docker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=< change it to your timezone > # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    volumes:
      - </path/to/folder>/tachidesk:/root/.local/share/Tachidesk
    ports:
      - 4567:4567
    restart: unless-stopped
