name: Manual Build Tag Images

on:
  workflow_dispatch:

env:
  startup_script_stable_url: 'https://raw.githubusercontent.com/arbuilder/Tachidesk-docker/main/startup_script.sh'
  build_tachidesk_tag: 'v0.3.7'
  build_tachidesk_url: 'https://github.com/Suwayomi/Tachidesk/releases/download/v0.3.7/Tachidesk-v0.3.7-r539.jar'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
          fetch-depth: 0
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: get release metadata
        id: get_release_metadata
        run: |
          cd main
          stable_url=${{ env.build_tachidesk_url }}
          stable_var=$(echo $stable_url | grep -o "Tachidesk-.*.jar" | sed -e's/Tachidesk-\|.jar//g')
          stable_commit=$(echo $stable_var | cut -f2 -d"r")
          stable_tag=${{ env.build_tachidesk_tag }}
          stable_filename=Tachidesk-${stable_var}.jar
          stable_version=$(echo $stable_tag | cut -c2-)
          echo "::set-output name=stable_url::$stable_url"
          echo "::set-output name=stable_commit::$stable_commit"
          echo "::set-output name=stable_tag::$stable_tag"
          echo "::set-output name=stable_filename::$stable_filename"
          echo "::set-output name=stable_version::$stable_version"
          echo "::set-output name=stable_var::$stable_var"
          tachidesk_docker_git_commit=$(git rev-list --count HEAD)
          echo "::set-output name=tachidesk_docker_git_commit::$tachidesk_docker_git_commit"
          build_date=$(date "+%F")
          echo "::set-output name=build_date::$build_date"

      - name: Build and push stable
        if: env.build_tachidesk_tag != ''     
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          file: scripts/dockerfiles/Git_Actions-Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            BASE_IMAGE=openjdk:latest
            BUILD_DATE=${{ steps.get_release_metadata.outputs.build_date }}
            IMAGE_VERSION=${{ steps.get_release_metadata.outputs.stable_version }}
            IMAGE_TYPE=stable
            TACHIDESK_GIT_COMMIT=${{ steps.get_release_metadata.outputs.stable_commit }}
            TACHIDESK_RELEASE_TAG=${{ env.build_tachidesk_tag }}
            TACHIDESK_RELEASE_DOWNLOAD_URL=${{ steps.get_release_metadata.outputs.stable_url }}
            TACHIDESK_FILENAME=${{ steps.get_release_metadata.outputs.stable_filename }}
            STARTUP_SCRIPT_URL=${{ env.startup_script_url }}
            TACHIDESK_DOCKER_GIT_COMMIT=${{ steps.get_release_metadata.outputs.tachidesk_docker_git_commit }}
          tags: |
            ${{ env.build_owner_docker }}/${{ env.build_repo_docker }}:${{ env.build_tachidesk_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
